#!/bin/bash

# Install metriculous in editable mode
pip install .

# Support jupytext files on mybinder.org:
# https://jupytext.readthedocs.io/en/latest/faq.html#can-i-use-jupytext-with-jupyter-hub-binder-nteract-colab-saturn-or-azure
pip install jupytext
jupyter lab build
